// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: broker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session messages
type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl     string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	HarFile       string                 `protobuf:"bytes,2,opt,name=har_file,json=harFile,proto3" json:"har_file,omitempty"`
	CookiesJar    string                 `protobuf:"bytes,3,opt,name=cookies_jar,json=cookiesJar,proto3" json:"cookies_jar,omitempty"`
	Headless      bool                   `protobuf:"varint,4,opt,name=headless,proto3" json:"headless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSessionRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *OpenSessionRequest) GetHarFile() string {
	if x != nil {
		return x.HarFile
	}
	return ""
}

func (x *OpenSessionRequest) GetCookiesJar() string {
	if x != nil {
		return x.CookiesJar
	}
	return ""
}

func (x *OpenSessionRequest) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,2,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenSessionResponse) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type AttachSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachSessionRequest) Reset() {
	*x = AttachSessionRequest{}
	mi := &file_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachSessionRequest) ProtoMessage() {}

func (x *AttachSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachSessionRequest.ProtoReflect.Descriptor instead.
func (*AttachSessionRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{2}
}

func (x *AttachSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AttachSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,1,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachSessionResponse) Reset() {
	*x = AttachSessionResponse{}
	mi := &file_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachSessionResponse) ProtoMessage() {}

func (x *AttachSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachSessionResponse.ProtoReflect.Descriptor instead.
func (*AttachSessionResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{3}
}

func (x *AttachSessionResponse) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type DetachSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachSessionRequest) Reset() {
	*x = DetachSessionRequest{}
	mi := &file_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachSessionRequest) ProtoMessage() {}

func (x *DetachSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachSessionRequest.ProtoReflect.Descriptor instead.
func (*DetachSessionRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{4}
}

func (x *DetachSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DetachSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachSessionResponse) Reset() {
	*x = DetachSessionResponse{}
	mi := &file_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachSessionResponse) ProtoMessage() {}

func (x *DetachSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachSessionResponse.ProtoReflect.Descriptor instead.
func (*DetachSessionResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{5}
}

func (x *DetachSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{6}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{7}
}

func (x *CloseSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_broker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,1,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_broker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionResponse) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionData   *SessionData           `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_broker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionRequest) GetSessionData() *SessionData {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type UpdateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
	mi := &file_broker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	SessionData   *SessionData           `protobuf:"bytes,3,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_broker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{12}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *SessionInfo) GetSessionData() *SessionData {
	if x != nil {
		return x.SessionData
	}
	return nil
}

func (x *SessionInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SessionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookies       map[string]string      `protobuf:"bytes,1,rep,name=cookies,proto3" json:"cookies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CsrfToken     string                 `protobuf:"bytes,3,opt,name=csrf_token,json=csrfToken,proto3" json:"csrf_token,omitempty"`
	Storage       map[string]string      `protobuf:"bytes,4,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionData) Reset() {
	*x = SessionData{}
	mi := &file_broker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionData) ProtoMessage() {}

func (x *SessionData) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionData.ProtoReflect.Descriptor instead.
func (*SessionData) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{13}
}

func (x *SessionData) GetCookies() map[string]string {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *SessionData) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SessionData) GetCsrfToken() string {
	if x != nil {
		return x.CsrfToken
	}
	return ""
}

func (x *SessionData) GetStorage() map[string]string {
	if x != nil {
		return x.Storage
	}
	return nil
}

// Step messages
type PushStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Step          *Step                  `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStepRequest) Reset() {
	*x = PushStepRequest{}
	mi := &file_broker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStepRequest) ProtoMessage() {}

func (x *PushStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStepRequest.ProtoReflect.Descriptor instead.
func (*PushStepRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{14}
}

func (x *PushStepRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PushStepRequest) GetStep() *Step {
	if x != nil {
		return x.Step
	}
	return nil
}

type PushStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Queued        bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStepResponse) Reset() {
	*x = PushStepResponse{}
	mi := &file_broker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStepResponse) ProtoMessage() {}

func (x *PushStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStepResponse.ProtoReflect.Descriptor instead.
func (*PushStepResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{15}
}

func (x *PushStepResponse) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *PushStepResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

type CancelStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStepRequest) Reset() {
	*x = CancelStepRequest{}
	mi := &file_broker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStepRequest) ProtoMessage() {}

func (x *CancelStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStepRequest.ProtoReflect.Descriptor instead.
func (*CancelStepRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{16}
}

func (x *CancelStepRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelStepRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type CancelStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStepResponse) Reset() {
	*x = CancelStepResponse{}
	mi := &file_broker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStepResponse) ProtoMessage() {}

func (x *CancelStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStepResponse.ProtoReflect.Descriptor instead.
func (*CancelStepResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{17}
}

func (x *CancelStepResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type GetStepStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStepStatusRequest) Reset() {
	*x = GetStepStatusRequest{}
	mi := &file_broker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStepStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStepStatusRequest) ProtoMessage() {}

func (x *GetStepStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStepStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStepStatusRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{18}
}

func (x *GetStepStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetStepStatusRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type GetStepStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StepStatus            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStepStatusResponse) Reset() {
	*x = GetStepStatusResponse{}
	mi := &file_broker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStepStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStepStatusResponse) ProtoMessage() {}

func (x *GetStepStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStepStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStepStatusResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{19}
}

func (x *GetStepStatusResponse) GetStatus() *StepStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_broker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{20}
}

func (x *StreamEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamEventsRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type Step struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Inputs         map[string]string      `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Guards         map[string]string      `protobuf:"bytes,4,rep,name=guards,proto3" json:"guards,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Effects        map[string]string      `protobuf:"bytes,5,rep,name=effects,proto3" json:"effects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryCount     int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	OnSuccess      []string               `protobuf:"bytes,8,rep,name=on_success,json=onSuccess,proto3" json:"on_success,omitempty"`
	OnFailure      []string               `protobuf:"bytes,9,rep,name=on_failure,json=onFailure,proto3" json:"on_failure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_broker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{21}
}

func (x *Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Step) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Step) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Step) GetGuards() map[string]string {
	if x != nil {
		return x.Guards
	}
	return nil
}

func (x *Step) GetEffects() map[string]string {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *Step) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Step) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Step) GetOnSuccess() []string {
	if x != nil {
		return x.OnSuccess
	}
	return nil
}

func (x *Step) GetOnFailure() []string {
	if x != nil {
		return x.OnFailure
	}
	return nil
}

type StepStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // PENDING, RUNNING, COMPLETED, FAILED, CANCELLED
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStatus) Reset() {
	*x = StepStatus{}
	mi := &file_broker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStatus) ProtoMessage() {}

func (x *StepStatus) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStatus.ProtoReflect.Descriptor instead.
func (*StepStatus) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{22}
}

func (x *StepStatus) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StepStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StepStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Event messages
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // STEP_STARTED, STEP_COMPLETED, STEP_FAILED, ARTIFACT_SAVED, FINDING_CREATED
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_broker_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{23}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Artifact messages
type PushArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushArtifactRequest) Reset() {
	*x = PushArtifactRequest{}
	mi := &file_broker_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushArtifactRequest) ProtoMessage() {}

func (x *PushArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushArtifactRequest.ProtoReflect.Descriptor instead.
func (*PushArtifactRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{24}
}

func (x *PushArtifactRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PushArtifactRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *PushArtifactRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PushArtifactRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushArtifactRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushArtifactRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PushArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Saved         bool                   `protobuf:"varint,2,opt,name=saved,proto3" json:"saved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushArtifactResponse) Reset() {
	*x = PushArtifactResponse{}
	mi := &file_broker_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushArtifactResponse) ProtoMessage() {}

func (x *PushArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushArtifactResponse.ProtoReflect.Descriptor instead.
func (*PushArtifactResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{25}
}

func (x *PushArtifactResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *PushArtifactResponse) GetSaved() bool {
	if x != nil {
		return x.Saved
	}
	return false
}

type GetArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_broker_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{26}
}

func (x *GetArtifactRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type GetArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *ArtifactInfo          `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactResponse) Reset() {
	*x = GetArtifactResponse{}
	mi := &file_broker_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactResponse) ProtoMessage() {}

func (x *GetArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{27}
}

func (x *GetArtifactResponse) GetArtifact() *ArtifactInfo {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GetArtifactResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_broker_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{28}
}

func (x *ListArtifactsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListArtifactsRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ListArtifactsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactInfo        `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_broker_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{29}
}

func (x *ListArtifactsResponse) GetArtifacts() []*ArtifactInfo {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactInfo) Reset() {
	*x = ArtifactInfo{}
	mi := &file_broker_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactInfo) ProtoMessage() {}

func (x *ArtifactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactInfo.ProtoReflect.Descriptor instead.
func (*ArtifactInfo) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{30}
}

func (x *ArtifactInfo) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ArtifactInfo) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ArtifactInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ArtifactInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ArtifactInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ArtifactInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_broker_proto protoreflect.FileDescriptor

const file_broker_proto_rawDesc = "" +
	"\n" +
	"\fbroker.proto\x12\x1bowaspattacksimulator.broker\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\x12OpenSessionRequest\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\x12\x19\n" +
	"\bhar_file\x18\x02 \x01(\tR\aharFile\x12\x1f\n" +
	"\vcookies_jar\x18\x03 \x01(\tR\n" +
	"cookiesJar\x12\x1a\n" +
	"\bheadless\x18\x04 \x01(\bR\bheadless\"\x81\x01\n" +
	"\x13OpenSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12K\n" +
	"\fsession_info\x18\x02 \x01(\v2(.owaspattacksimulator.broker.SessionInfoR\vsessionInfo\"5\n" +
	"\x14AttachSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"d\n" +
	"\x15AttachSessionResponse\x12K\n" +
	"\fsession_info\x18\x01 \x01(\v2(.owaspattacksimulator.broker.SessionInfoR\vsessionInfo\"5\n" +
	"\x14DetachSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"1\n" +
	"\x15DetachSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"0\n" +
	"\x14CloseSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"a\n" +
	"\x12GetSessionResponse\x12K\n" +
	"\fsession_info\x18\x01 \x01(\v2(.owaspattacksimulator.broker.SessionInfoR\vsessionInfo\"\x82\x01\n" +
	"\x14UpdateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12K\n" +
	"\fsession_data\x18\x02 \x01(\v2(.owaspattacksimulator.broker.SessionDataR\vsessionData\"1\n" +
	"\x15UpdateSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12K\n" +
	"\fsession_data\x18\x03 \x01(\v2(.owaspattacksimulator.broker.SessionDataR\vsessionData\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd3\x03\n" +
	"\vSessionData\x12O\n" +
	"\acookies\x18\x01 \x03(\v25.owaspattacksimulator.broker.SessionData.CookiesEntryR\acookies\x12O\n" +
	"\aheaders\x18\x02 \x03(\v25.owaspattacksimulator.broker.SessionData.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"csrf_token\x18\x03 \x01(\tR\tcsrfToken\x12O\n" +
	"\astorage\x18\x04 \x03(\v25.owaspattacksimulator.broker.SessionData.StorageEntryR\astorage\x1a:\n" +
	"\fCookiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fStorageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x0fPushStepRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x125\n" +
	"\x04step\x18\x02 \x01(\v2!.owaspattacksimulator.broker.StepR\x04step\"C\n" +
	"\x10PushStepResponse\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\bR\x06queued\"K\n" +
	"\x11CancelStepRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\"2\n" +
	"\x12CancelStepResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"N\n" +
	"\x14GetStepStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\"X\n" +
	"\x15GetStepStatusResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\v2'.owaspattacksimulator.broker.StepStatusR\x06status\"M\n" +
	"\x13StreamEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\"\xbc\x04\n" +
	"\x04Step\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12E\n" +
	"\x06inputs\x18\x03 \x03(\v2-.owaspattacksimulator.broker.Step.InputsEntryR\x06inputs\x12E\n" +
	"\x06guards\x18\x04 \x03(\v2-.owaspattacksimulator.broker.Step.GuardsEntryR\x06guards\x12H\n" +
	"\aeffects\x18\x05 \x03(\v2..owaspattacksimulator.broker.Step.EffectsEntryR\aeffects\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"on_success\x18\b \x03(\tR\tonSuccess\x12\x1d\n" +
	"\n" +
	"on_failure\x18\t \x03(\tR\tonFailure\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vGuardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fEffectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\n" +
	"StepStatus\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xc2\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa2\x02\n" +
	"\x13PushArtifactRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12Z\n" +
	"\bmetadata\x18\x06 \x03(\v2>.owaspattacksimulator.broker.PushArtifactRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x14PushArtifactResponse\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x14\n" +
	"\x05saved\x18\x02 \x01(\bR\x05saved\"T\n" +
	"\x12GetArtifactRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\"p\n" +
	"\x13GetArtifactResponse\x12E\n" +
	"\bartifact\x18\x01 \x01(\v2).owaspattacksimulator.broker.ArtifactInfoR\bartifact\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"b\n" +
	"\x14ListArtifactsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"`\n" +
	"\x15ListArtifactsResponse\x12G\n" +
	"\tartifacts\x18\x01 \x03(\v2).owaspattacksimulator.broker.ArtifactInfoR\tartifacts\"\xdc\x02\n" +
	"\fArtifactInfo\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12S\n" +
	"\bmetadata\x18\x06 \x03(\v27.owaspattacksimulator.broker.ArtifactInfo.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xce\x05\n" +
	"\x0eSessionService\x12p\n" +
	"\vOpenSession\x12/.owaspattacksimulator.broker.OpenSessionRequest\x1a0.owaspattacksimulator.broker.OpenSessionResponse\x12v\n" +
	"\rAttachSession\x121.owaspattacksimulator.broker.AttachSessionRequest\x1a2.owaspattacksimulator.broker.AttachSessionResponse\x12v\n" +
	"\rDetachSession\x121.owaspattacksimulator.broker.DetachSessionRequest\x1a2.owaspattacksimulator.broker.DetachSessionResponse\x12s\n" +
	"\fCloseSession\x120.owaspattacksimulator.broker.CloseSessionRequest\x1a1.owaspattacksimulator.broker.CloseSessionResponse\x12m\n" +
	"\n" +
	"GetSession\x12..owaspattacksimulator.broker.GetSessionRequest\x1a/.owaspattacksimulator.broker.GetSessionResponse\x12v\n" +
	"\rUpdateSession\x121.owaspattacksimulator.broker.UpdateSessionRequest\x1a2.owaspattacksimulator.broker.UpdateSessionResponse2\xc5\x03\n" +
	"\vStepService\x12g\n" +
	"\bPushStep\x12,.owaspattacksimulator.broker.PushStepRequest\x1a-.owaspattacksimulator.broker.PushStepResponse\x12m\n" +
	"\n" +
	"CancelStep\x12..owaspattacksimulator.broker.CancelStepRequest\x1a/.owaspattacksimulator.broker.CancelStepResponse\x12v\n" +
	"\rGetStepStatus\x121.owaspattacksimulator.broker.GetStepStatusRequest\x1a2.owaspattacksimulator.broker.GetStepStatusResponse\x12f\n" +
	"\fStreamEvents\x120.owaspattacksimulator.broker.StreamEventsRequest\x1a\".owaspattacksimulator.broker.Event0\x012\xf0\x02\n" +
	"\x0fArtifactService\x12s\n" +
	"\fPushArtifact\x120.owaspattacksimulator.broker.PushArtifactRequest\x1a1.owaspattacksimulator.broker.PushArtifactResponse\x12p\n" +
	"\vGetArtifact\x12/.owaspattacksimulator.broker.GetArtifactRequest\x1a0.owaspattacksimulator.broker.GetArtifactResponse\x12v\n" +
	"\rListArtifacts\x121.owaspattacksimulator.broker.ListArtifactsRequest\x1a2.owaspattacksimulator.broker.ListArtifactsResponseB1Z/github.com/owaspattacksimulator/api/proto;protob\x06proto3"

var (
	file_broker_proto_rawDescOnce sync.Once
	file_broker_proto_rawDescData []byte
)

func file_broker_proto_rawDescGZIP() []byte {
	file_broker_proto_rawDescOnce.Do(func() {
		file_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broker_proto_rawDesc), len(file_broker_proto_rawDesc)))
	})
	return file_broker_proto_rawDescData
}

var file_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_broker_proto_goTypes = []any{
	(*OpenSessionRequest)(nil),    // 0: owaspattacksimulator.broker.OpenSessionRequest
	(*OpenSessionResponse)(nil),   // 1: owaspattacksimulator.broker.OpenSessionResponse
	(*AttachSessionRequest)(nil),  // 2: owaspattacksimulator.broker.AttachSessionRequest
	(*AttachSessionResponse)(nil), // 3: owaspattacksimulator.broker.AttachSessionResponse
	(*DetachSessionRequest)(nil),  // 4: owaspattacksimulator.broker.DetachSessionRequest
	(*DetachSessionResponse)(nil), // 5: owaspattacksimulator.broker.DetachSessionResponse
	(*CloseSessionRequest)(nil),   // 6: owaspattacksimulator.broker.CloseSessionRequest
	(*CloseSessionResponse)(nil),  // 7: owaspattacksimulator.broker.CloseSessionResponse
	(*GetSessionRequest)(nil),     // 8: owaspattacksimulator.broker.GetSessionRequest
	(*GetSessionResponse)(nil),    // 9: owaspattacksimulator.broker.GetSessionResponse
	(*UpdateSessionRequest)(nil),  // 10: owaspattacksimulator.broker.UpdateSessionRequest
	(*UpdateSessionResponse)(nil), // 11: owaspattacksimulator.broker.UpdateSessionResponse
	(*SessionInfo)(nil),           // 12: owaspattacksimulator.broker.SessionInfo
	(*SessionData)(nil),           // 13: owaspattacksimulator.broker.SessionData
	(*PushStepRequest)(nil),       // 14: owaspattacksimulator.broker.PushStepRequest
	(*PushStepResponse)(nil),      // 15: owaspattacksimulator.broker.PushStepResponse
	(*CancelStepRequest)(nil),     // 16: owaspattacksimulator.broker.CancelStepRequest
	(*CancelStepResponse)(nil),    // 17: owaspattacksimulator.broker.CancelStepResponse
	(*GetStepStatusRequest)(nil),  // 18: owaspattacksimulator.broker.GetStepStatusRequest
	(*GetStepStatusResponse)(nil), // 19: owaspattacksimulator.broker.GetStepStatusResponse
	(*StreamEventsRequest)(nil),   // 20: owaspattacksimulator.broker.StreamEventsRequest
	(*Step)(nil),                  // 21: owaspattacksimulator.broker.Step
	(*StepStatus)(nil),            // 22: owaspattacksimulator.broker.StepStatus
	(*Event)(nil),                 // 23: owaspattacksimulator.broker.Event
	(*PushArtifactRequest)(nil),   // 24: owaspattacksimulator.broker.PushArtifactRequest
	(*PushArtifactResponse)(nil),  // 25: owaspattacksimulator.broker.PushArtifactResponse
	(*GetArtifactRequest)(nil),    // 26: owaspattacksimulator.broker.GetArtifactRequest
	(*GetArtifactResponse)(nil),   // 27: owaspattacksimulator.broker.GetArtifactResponse
	(*ListArtifactsRequest)(nil),  // 28: owaspattacksimulator.broker.ListArtifactsRequest
	(*ListArtifactsResponse)(nil), // 29: owaspattacksimulator.broker.ListArtifactsResponse
	(*ArtifactInfo)(nil),          // 30: owaspattacksimulator.broker.ArtifactInfo
	nil,                           // 31: owaspattacksimulator.broker.SessionData.CookiesEntry
	nil,                           // 32: owaspattacksimulator.broker.SessionData.HeadersEntry
	nil,                           // 33: owaspattacksimulator.broker.SessionData.StorageEntry
	nil,                           // 34: owaspattacksimulator.broker.Step.InputsEntry
	nil,                           // 35: owaspattacksimulator.broker.Step.GuardsEntry
	nil,                           // 36: owaspattacksimulator.broker.Step.EffectsEntry
	nil,                           // 37: owaspattacksimulator.broker.PushArtifactRequest.MetadataEntry
	nil,                           // 38: owaspattacksimulator.broker.ArtifactInfo.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 39: google.protobuf.Timestamp
}
var file_broker_proto_depIdxs = []int32{
	12, // 0: owaspattacksimulator.broker.OpenSessionResponse.session_info:type_name -> owaspattacksimulator.broker.SessionInfo
	12, // 1: owaspattacksimulator.broker.AttachSessionResponse.session_info:type_name -> owaspattacksimulator.broker.SessionInfo
	12, // 2: owaspattacksimulator.broker.GetSessionResponse.session_info:type_name -> owaspattacksimulator.broker.SessionInfo
	13, // 3: owaspattacksimulator.broker.UpdateSessionRequest.session_data:type_name -> owaspattacksimulator.broker.SessionData
	13, // 4: owaspattacksimulator.broker.SessionInfo.session_data:type_name -> owaspattacksimulator.broker.SessionData
	39, // 5: owaspattacksimulator.broker.SessionInfo.created_at:type_name -> google.protobuf.Timestamp
	39, // 6: owaspattacksimulator.broker.SessionInfo.updated_at:type_name -> google.protobuf.Timestamp
	31, // 7: owaspattacksimulator.broker.SessionData.cookies:type_name -> owaspattacksimulator.broker.SessionData.CookiesEntry
	32, // 8: owaspattacksimulator.broker.SessionData.headers:type_name -> owaspattacksimulator.broker.SessionData.HeadersEntry
	33, // 9: owaspattacksimulator.broker.SessionData.storage:type_name -> owaspattacksimulator.broker.SessionData.StorageEntry
	21, // 10: owaspattacksimulator.broker.PushStepRequest.step:type_name -> owaspattacksimulator.broker.Step
	22, // 11: owaspattacksimulator.broker.GetStepStatusResponse.status:type_name -> owaspattacksimulator.broker.StepStatus
	34, // 12: owaspattacksimulator.broker.Step.inputs:type_name -> owaspattacksimulator.broker.Step.InputsEntry
	35, // 13: owaspattacksimulator.broker.Step.guards:type_name -> owaspattacksimulator.broker.Step.GuardsEntry
	36, // 14: owaspattacksimulator.broker.Step.effects:type_name -> owaspattacksimulator.broker.Step.EffectsEntry
	39, // 15: owaspattacksimulator.broker.StepStatus.started_at:type_name -> google.protobuf.Timestamp
	39, // 16: owaspattacksimulator.broker.StepStatus.completed_at:type_name -> google.protobuf.Timestamp
	39, // 17: owaspattacksimulator.broker.Event.timestamp:type_name -> google.protobuf.Timestamp
	37, // 18: owaspattacksimulator.broker.PushArtifactRequest.metadata:type_name -> owaspattacksimulator.broker.PushArtifactRequest.MetadataEntry
	30, // 19: owaspattacksimulator.broker.GetArtifactResponse.artifact:type_name -> owaspattacksimulator.broker.ArtifactInfo
	30, // 20: owaspattacksimulator.broker.ListArtifactsResponse.artifacts:type_name -> owaspattacksimulator.broker.ArtifactInfo
	38, // 21: owaspattacksimulator.broker.ArtifactInfo.metadata:type_name -> owaspattacksimulator.broker.ArtifactInfo.MetadataEntry
	39, // 22: owaspattacksimulator.broker.ArtifactInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 23: owaspattacksimulator.broker.SessionService.OpenSession:input_type -> owaspattacksimulator.broker.OpenSessionRequest
	2,  // 24: owaspattacksimulator.broker.SessionService.AttachSession:input_type -> owaspattacksimulator.broker.AttachSessionRequest
	4,  // 25: owaspattacksimulator.broker.SessionService.DetachSession:input_type -> owaspattacksimulator.broker.DetachSessionRequest
	6,  // 26: owaspattacksimulator.broker.SessionService.CloseSession:input_type -> owaspattacksimulator.broker.CloseSessionRequest
	8,  // 27: owaspattacksimulator.broker.SessionService.GetSession:input_type -> owaspattacksimulator.broker.GetSessionRequest
	10, // 28: owaspattacksimulator.broker.SessionService.UpdateSession:input_type -> owaspattacksimulator.broker.UpdateSessionRequest
	14, // 29: owaspattacksimulator.broker.StepService.PushStep:input_type -> owaspattacksimulator.broker.PushStepRequest
	16, // 30: owaspattacksimulator.broker.StepService.CancelStep:input_type -> owaspattacksimulator.broker.CancelStepRequest
	18, // 31: owaspattacksimulator.broker.StepService.GetStepStatus:input_type -> owaspattacksimulator.broker.GetStepStatusRequest
	20, // 32: owaspattacksimulator.broker.StepService.StreamEvents:input_type -> owaspattacksimulator.broker.StreamEventsRequest
	24, // 33: owaspattacksimulator.broker.ArtifactService.PushArtifact:input_type -> owaspattacksimulator.broker.PushArtifactRequest
	26, // 34: owaspattacksimulator.broker.ArtifactService.GetArtifact:input_type -> owaspattacksimulator.broker.GetArtifactRequest
	28, // 35: owaspattacksimulator.broker.ArtifactService.ListArtifacts:input_type -> owaspattacksimulator.broker.ListArtifactsRequest
	1,  // 36: owaspattacksimulator.broker.SessionService.OpenSession:output_type -> owaspattacksimulator.broker.OpenSessionResponse
	3,  // 37: owaspattacksimulator.broker.SessionService.AttachSession:output_type -> owaspattacksimulator.broker.AttachSessionResponse
	5,  // 38: owaspattacksimulator.broker.SessionService.DetachSession:output_type -> owaspattacksimulator.broker.DetachSessionResponse
	7,  // 39: owaspattacksimulator.broker.SessionService.CloseSession:output_type -> owaspattacksimulator.broker.CloseSessionResponse
	9,  // 40: owaspattacksimulator.broker.SessionService.GetSession:output_type -> owaspattacksimulator.broker.GetSessionResponse
	11, // 41: owaspattacksimulator.broker.SessionService.UpdateSession:output_type -> owaspattacksimulator.broker.UpdateSessionResponse
	15, // 42: owaspattacksimulator.broker.StepService.PushStep:output_type -> owaspattacksimulator.broker.PushStepResponse
	17, // 43: owaspattacksimulator.broker.StepService.CancelStep:output_type -> owaspattacksimulator.broker.CancelStepResponse
	19, // 44: owaspattacksimulator.broker.StepService.GetStepStatus:output_type -> owaspattacksimulator.broker.GetStepStatusResponse
	23, // 45: owaspattacksimulator.broker.StepService.StreamEvents:output_type -> owaspattacksimulator.broker.Event
	25, // 46: owaspattacksimulator.broker.ArtifactService.PushArtifact:output_type -> owaspattacksimulator.broker.PushArtifactResponse
	27, // 47: owaspattacksimulator.broker.ArtifactService.GetArtifact:output_type -> owaspattacksimulator.broker.GetArtifactResponse
	29, // 48: owaspattacksimulator.broker.ArtifactService.ListArtifacts:output_type -> owaspattacksimulator.broker.ListArtifactsResponse
	36, // [36:49] is the sub-list for method output_type
	23, // [23:36] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_broker_proto_init() }
func file_broker_proto_init() {
	if File_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broker_proto_rawDesc), len(file_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_broker_proto_goTypes,
		DependencyIndexes: file_broker_proto_depIdxs,
		MessageInfos:      file_broker_proto_msgTypes,
	}.Build()
	File_broker_proto = out.File
	file_broker_proto_goTypes = nil
	file_broker_proto_depIdxs = nil
}
