// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: scenario.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scenario validation
type ValidateScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioData  []byte                 `protobuf:"bytes,1,opt,name=scenario_data,json=scenarioData,proto3" json:"scenario_data,omitempty"` // YAML content
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                                 // "yaml" or "json"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateScenarioRequest) Reset() {
	*x = ValidateScenarioRequest{}
	mi := &file_scenario_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateScenarioRequest) ProtoMessage() {}

func (x *ValidateScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateScenarioRequest.ProtoReflect.Descriptor instead.
func (*ValidateScenarioRequest) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateScenarioRequest) GetScenarioData() []byte {
	if x != nil {
		return x.ScenarioData
	}
	return nil
}

func (x *ValidateScenarioRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ValidateScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []*ValidationWarning   `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateScenarioResponse) Reset() {
	*x = ValidateScenarioResponse{}
	mi := &file_scenario_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateScenarioResponse) ProtoMessage() {}

func (x *ValidateScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateScenarioResponse.ProtoReflect.Descriptor instead.
func (*ValidateScenarioResponse) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateScenarioResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateScenarioResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateScenarioResponse) GetWarnings() []*ValidationWarning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_scenario_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ValidationError) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type ValidationWarning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationWarning) Reset() {
	*x = ValidationWarning{}
	mi := &file_scenario_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationWarning) ProtoMessage() {}

func (x *ValidationWarning) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationWarning.ProtoReflect.Descriptor instead.
func (*ValidationWarning) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{3}
}

func (x *ValidationWarning) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationWarning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationWarning) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ValidationWarning) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Scenario parsing
type ParseScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioData  []byte                 `protobuf:"bytes,1,opt,name=scenario_data,json=scenarioData,proto3" json:"scenario_data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseScenarioRequest) Reset() {
	*x = ParseScenarioRequest{}
	mi := &file_scenario_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseScenarioRequest) ProtoMessage() {}

func (x *ParseScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseScenarioRequest.ProtoReflect.Descriptor instead.
func (*ParseScenarioRequest) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{4}
}

func (x *ParseScenarioRequest) GetScenarioData() []byte {
	if x != nil {
		return x.ScenarioData
	}
	return nil
}

func (x *ParseScenarioRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ParseScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *Scenario              `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Errors        []*ParseError          `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseScenarioResponse) Reset() {
	*x = ParseScenarioResponse{}
	mi := &file_scenario_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseScenarioResponse) ProtoMessage() {}

func (x *ParseScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseScenarioResponse.ProtoReflect.Descriptor instead.
func (*ParseScenarioResponse) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{5}
}

func (x *ParseScenarioResponse) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *ParseScenarioResponse) GetErrors() []*ParseError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ParseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseError) Reset() {
	*x = ParseError{}
	mi := &file_scenario_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseError) ProtoMessage() {}

func (x *ParseError) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseError.ProtoReflect.Descriptor instead.
func (*ParseError) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{6}
}

func (x *ParseError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParseError) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ParseError) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Scenario execution
type ExecuteScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scenario      *Scenario              `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Config        *ExecutionConfig       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteScenarioRequest) Reset() {
	*x = ExecuteScenarioRequest{}
	mi := &file_scenario_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScenarioRequest) ProtoMessage() {}

func (x *ExecuteScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScenarioRequest.ProtoReflect.Descriptor instead.
func (*ExecuteScenarioRequest) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteScenarioRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteScenarioRequest) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *ExecuteScenarioRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ExecuteScenarioRequest) GetConfig() *ExecutionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ExecutionConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Concurrency    int32                  `protobuf:"varint,1,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	DryRun         bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	EnabledSteps   []string               `protobuf:"bytes,4,rep,name=enabled_steps,json=enabledSteps,proto3" json:"enabled_steps,omitempty"`
	DisabledSteps  []string               `protobuf:"bytes,5,rep,name=disabled_steps,json=disabledSteps,proto3" json:"disabled_steps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionConfig) Reset() {
	*x = ExecutionConfig{}
	mi := &file_scenario_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionConfig) ProtoMessage() {}

func (x *ExecutionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionConfig.ProtoReflect.Descriptor instead.
func (*ExecutionConfig) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionConfig) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *ExecutionConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecutionConfig) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ExecutionConfig) GetEnabledSteps() []string {
	if x != nil {
		return x.EnabledSteps
	}
	return nil
}

func (x *ExecutionConfig) GetDisabledSteps() []string {
	if x != nil {
		return x.DisabledSteps
	}
	return nil
}

// Scenario structure
type Scenario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Steps         []*ScenarioStep        `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_scenario_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{9}
}

func (x *Scenario) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Scenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scenario) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Scenario) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Scenario) GetSteps() []*ScenarioStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Scenario) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScenarioStep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Inputs         map[string]string      `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Guards         map[string]string      `protobuf:"bytes,6,rep,name=guards,proto3" json:"guards,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Effects        map[string]string      `protobuf:"bytes,7,rep,name=effects,proto3" json:"effects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryCount     int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	OnSuccess      []string               `protobuf:"bytes,10,rep,name=on_success,json=onSuccess,proto3" json:"on_success,omitempty"`
	OnFailure      []string               `protobuf:"bytes,11,rep,name=on_failure,json=onFailure,proto3" json:"on_failure,omitempty"`
	Children       []*ScenarioStep        `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"` // For control steps
	Metadata       map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScenarioStep) Reset() {
	*x = ScenarioStep{}
	mi := &file_scenario_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioStep) ProtoMessage() {}

func (x *ScenarioStep) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioStep.ProtoReflect.Descriptor instead.
func (*ScenarioStep) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{10}
}

func (x *ScenarioStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScenarioStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScenarioStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScenarioStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScenarioStep) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ScenarioStep) GetGuards() map[string]string {
	if x != nil {
		return x.Guards
	}
	return nil
}

func (x *ScenarioStep) GetEffects() map[string]string {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *ScenarioStep) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ScenarioStep) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ScenarioStep) GetOnSuccess() []string {
	if x != nil {
		return x.OnSuccess
	}
	return nil
}

func (x *ScenarioStep) GetOnFailure() []string {
	if x != nil {
		return x.OnFailure
	}
	return nil
}

func (x *ScenarioStep) GetChildren() []*ScenarioStep {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ScenarioStep) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Step types
type BrowserStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // navigate, fill, click, wait, screenshot, script
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Selector      string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	WaitCondition string                 `protobuf:"bytes,5,opt,name=wait_condition,json=waitCondition,proto3" json:"wait_condition,omitempty"` // networkidle, domcontentloaded, etc.
	Options       map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserStep) Reset() {
	*x = BrowserStep{}
	mi := &file_scenario_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserStep) ProtoMessage() {}

func (x *BrowserStep) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserStep.ProtoReflect.Descriptor instead.
func (*BrowserStep) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{11}
}

func (x *BrowserStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *BrowserStep) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BrowserStep) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *BrowserStep) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BrowserStep) GetWaitCondition() string {
	if x != nil {
		return x.WaitCondition
	}
	return ""
}

func (x *BrowserStep) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type SessionStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // update, save, restore
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // browser, file, manual
	Items         []string               `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`   // cookies, headers, storage
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStep) Reset() {
	*x = SessionStep{}
	mi := &file_scenario_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStep) ProtoMessage() {}

func (x *SessionStep) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStep.ProtoReflect.Descriptor instead.
func (*SessionStep) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{12}
}

func (x *SessionStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SessionStep) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SessionStep) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SessionStep) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type NetworkStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // request, mutate, attack, check
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Mutation      *MutationConfig        `protobuf:"bytes,7,opt,name=mutation,proto3" json:"mutation,omitempty"`
	Checks        *CheckConfig           `protobuf:"bytes,8,opt,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStep) Reset() {
	*x = NetworkStep{}
	mi := &file_scenario_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStep) ProtoMessage() {}

func (x *NetworkStep) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStep.ProtoReflect.Descriptor instead.
func (*NetworkStep) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *NetworkStep) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NetworkStep) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NetworkStep) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *NetworkStep) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NetworkStep) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *NetworkStep) GetMutation() *MutationConfig {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *NetworkStep) GetChecks() *CheckConfig {
	if x != nil {
		return x.Checks
	}
	return nil
}

type MutationConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Methods           []string               `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	Bodies            []string               `protobuf:"bytes,2,rep,name=bodies,proto3" json:"bodies,omitempty"`
	PayloadSets       []string               `protobuf:"bytes,3,rep,name=payload_sets,json=payloadSets,proto3" json:"payload_sets,omitempty"`
	MaxVariantsPerReq int32                  `protobuf:"varint,4,opt,name=max_variants_per_req,json=maxVariantsPerReq,proto3" json:"max_variants_per_req,omitempty"`
	Options           map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MutationConfig) Reset() {
	*x = MutationConfig{}
	mi := &file_scenario_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationConfig) ProtoMessage() {}

func (x *MutationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationConfig.ProtoReflect.Descriptor instead.
func (*MutationConfig) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{14}
}

func (x *MutationConfig) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *MutationConfig) GetBodies() []string {
	if x != nil {
		return x.Bodies
	}
	return nil
}

func (x *MutationConfig) GetPayloadSets() []string {
	if x != nil {
		return x.PayloadSets
	}
	return nil
}

func (x *MutationConfig) GetMaxVariantsPerReq() int32 {
	if x != nil {
		return x.MaxVariantsPerReq
	}
	return 0
}

func (x *MutationConfig) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CheckConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       []string               `protobuf:"bytes,1,rep,name=enabled,proto3" json:"enabled,omitempty"`
	Thresholds    map[string]string      `protobuf:"bytes,2,rep,name=thresholds,proto3" json:"thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConfig) Reset() {
	*x = CheckConfig{}
	mi := &file_scenario_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfig) ProtoMessage() {}

func (x *CheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfig.ProtoReflect.Descriptor instead.
func (*CheckConfig) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{15}
}

func (x *CheckConfig) GetEnabled() []string {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *CheckConfig) GetThresholds() map[string]string {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

func (x *CheckConfig) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CrawlStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // run, feed
	SeedUrl       string                 `protobuf:"bytes,2,opt,name=seed_url,json=seedUrl,proto3" json:"seed_url,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlStep) Reset() {
	*x = CrawlStep{}
	mi := &file_scenario_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlStep) ProtoMessage() {}

func (x *CrawlStep) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlStep.ProtoReflect.Descriptor instead.
func (*CrawlStep) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{16}
}

func (x *CrawlStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CrawlStep) GetSeedUrl() string {
	if x != nil {
		return x.SeedUrl
	}
	return ""
}

func (x *CrawlStep) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ControlStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // if, while, foreach
	Condition     string                 `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Body          []*ScenarioStep        `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	DataSet       []string               `protobuf:"bytes,4,rep,name=data_set,json=dataSet,proto3" json:"data_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStep) Reset() {
	*x = ControlStep{}
	mi := &file_scenario_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStep) ProtoMessage() {}

func (x *ControlStep) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStep.ProtoReflect.Descriptor instead.
func (*ControlStep) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{17}
}

func (x *ControlStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ControlStep) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *ControlStep) GetBody() []*ScenarioStep {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControlStep) GetDataSet() []string {
	if x != nil {
		return x.DataSet
	}
	return nil
}

type PluginStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStep) Reset() {
	*x = PluginStep{}
	mi := &file_scenario_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStep) ProtoMessage() {}

func (x *PluginStep) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStep.ProtoReflect.Descriptor instead.
func (*PluginStep) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{18}
}

func (x *PluginStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PluginStep) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Execution events
type ScenarioEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ScenarioId    string                 `protobuf:"bytes,3,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	StepId        string                 `protobuf:"bytes,4,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"` // SCENARIO_STARTED, STEP_STARTED, STEP_COMPLETED, STEP_FAILED, SCENARIO_COMPLETED
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioEvent) Reset() {
	*x = ScenarioEvent{}
	mi := &file_scenario_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioEvent) ProtoMessage() {}

func (x *ScenarioEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioEvent.ProtoReflect.Descriptor instead.
func (*ScenarioEvent) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{19}
}

func (x *ScenarioEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ScenarioEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScenarioEvent) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ScenarioEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ScenarioEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ScenarioEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ScenarioEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StepExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // PENDING, RUNNING, COMPLETED, FAILED, CANCELLED
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Results       map[string]string      `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecutionEvent) Reset() {
	*x = StepExecutionEvent{}
	mi := &file_scenario_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecutionEvent) ProtoMessage() {}

func (x *StepExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecutionEvent.ProtoReflect.Descriptor instead.
func (*StepExecutionEvent) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{20}
}

func (x *StepExecutionEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepExecutionEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StepExecutionEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StepExecutionEvent) GetResults() map[string]string {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *StepExecutionEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepExecutionEvent) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_scenario_proto protoreflect.FileDescriptor

const file_scenario_proto_rawDesc = "" +
	"\n" +
	"\x0escenario.proto\x12\x1dowaspattacksimulator.scenario\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x17ValidateScenarioRequest\x12#\n" +
	"\rscenario_data\x18\x01 \x01(\fR\fscenarioData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\xc6\x01\n" +
	"\x18ValidateScenarioResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12F\n" +
	"\x06errors\x18\x02 \x03(\v2..owaspattacksimulator.scenario.ValidationErrorR\x06errors\x12L\n" +
	"\bwarnings\x18\x03 \x03(\v20.owaspattacksimulator.scenario.ValidationWarningR\bwarnings\"m\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"o\n" +
	"\x11ValidationWarning\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"S\n" +
	"\x14ParseScenarioRequest\x12#\n" +
	"\rscenario_data\x18\x01 \x01(\fR\fscenarioData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\x9f\x01\n" +
	"\x15ParseScenarioResponse\x12C\n" +
	"\bscenario\x18\x01 \x01(\v2'.owaspattacksimulator.scenario.ScenarioR\bscenario\x12A\n" +
	"\x06errors\x18\x02 \x03(\v2).owaspattacksimulator.scenario.ParseErrorR\x06errors\"R\n" +
	"\n" +
	"ParseError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"\xe6\x02\n" +
	"\x16ExecuteScenarioRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12C\n" +
	"\bscenario\x18\x02 \x01(\v2'.owaspattacksimulator.scenario.ScenarioR\bscenario\x12b\n" +
	"\tvariables\x18\x03 \x03(\v2D.owaspattacksimulator.scenario.ExecuteScenarioRequest.VariablesEntryR\tvariables\x12F\n" +
	"\x06config\x18\x04 \x01(\v2..owaspattacksimulator.scenario.ExecutionConfigR\x06config\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x0fExecutionConfig\x12 \n" +
	"\vconcurrency\x18\x01 \x01(\x05R\vconcurrency\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12#\n" +
	"\renabled_steps\x18\x04 \x03(\tR\fenabledSteps\x12%\n" +
	"\x0edisabled_steps\x18\x05 \x03(\tR\rdisabledSteps\"\xc1\x03\n" +
	"\bScenario\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12T\n" +
	"\tvariables\x18\x04 \x03(\v26.owaspattacksimulator.scenario.Scenario.VariablesEntryR\tvariables\x12A\n" +
	"\x05steps\x18\x05 \x03(\v2+.owaspattacksimulator.scenario.ScenarioStepR\x05steps\x12Q\n" +
	"\bmetadata\x18\x06 \x03(\v25.owaspattacksimulator.scenario.Scenario.MetadataEntryR\bmetadata\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x06\n" +
	"\fScenarioStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12O\n" +
	"\x06inputs\x18\x05 \x03(\v27.owaspattacksimulator.scenario.ScenarioStep.InputsEntryR\x06inputs\x12O\n" +
	"\x06guards\x18\x06 \x03(\v27.owaspattacksimulator.scenario.ScenarioStep.GuardsEntryR\x06guards\x12R\n" +
	"\aeffects\x18\a \x03(\v28.owaspattacksimulator.scenario.ScenarioStep.EffectsEntryR\aeffects\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"on_success\x18\n" +
	" \x03(\tR\tonSuccess\x12\x1d\n" +
	"\n" +
	"on_failure\x18\v \x03(\tR\tonFailure\x12G\n" +
	"\bchildren\x18\f \x03(\v2+.owaspattacksimulator.scenario.ScenarioStepR\bchildren\x12U\n" +
	"\bmetadata\x18\r \x03(\v29.owaspattacksimulator.scenario.ScenarioStep.MetadataEntryR\bmetadata\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vGuardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fEffectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x02\n" +
	"\vBrowserStep\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12%\n" +
	"\x0ewait_condition\x18\x05 \x01(\tR\rwaitCondition\x12Q\n" +
	"\aoptions\x18\x06 \x03(\v27.owaspattacksimulator.scenario.BrowserStep.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\vSessionStep\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05items\x18\x03 \x03(\tR\x05items\x12H\n" +
	"\x04data\x18\x04 \x03(\v24.owaspattacksimulator.scenario.SessionStep.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x03\n" +
	"\vNetworkStep\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12Q\n" +
	"\aheaders\x18\x04 \x03(\v27.owaspattacksimulator.scenario.NetworkStep.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12I\n" +
	"\bmutation\x18\a \x01(\v2-.owaspattacksimulator.scenario.MutationConfigR\bmutation\x12B\n" +
	"\x06checks\x18\b \x01(\v2*.owaspattacksimulator.scenario.CheckConfigR\x06checks\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x02\n" +
	"\x0eMutationConfig\x12\x18\n" +
	"\amethods\x18\x01 \x03(\tR\amethods\x12\x16\n" +
	"\x06bodies\x18\x02 \x03(\tR\x06bodies\x12!\n" +
	"\fpayload_sets\x18\x03 \x03(\tR\vpayloadSets\x12/\n" +
	"\x14max_variants_per_req\x18\x04 \x01(\x05R\x11maxVariantsPerReq\x12T\n" +
	"\aoptions\x18\x05 \x03(\v2:.owaspattacksimulator.scenario.MutationConfig.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x02\n" +
	"\vCheckConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x03(\tR\aenabled\x12Z\n" +
	"\n" +
	"thresholds\x18\x02 \x03(\v2:.owaspattacksimulator.scenario.CheckConfig.ThresholdsEntryR\n" +
	"thresholds\x12Q\n" +
	"\aoptions\x18\x03 \x03(\v27.owaspattacksimulator.scenario.CheckConfig.OptionsEntryR\aoptions\x1a=\n" +
	"\x0fThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\tCrawlStep\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x19\n" +
	"\bseed_url\x18\x02 \x01(\tR\aseedUrl\x12O\n" +
	"\aoptions\x18\x03 \x03(\v25.owaspattacksimulator.scenario.CrawlStep.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\vControlStep\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\x12?\n" +
	"\x04body\x18\x03 \x03(\v2+.owaspattacksimulator.scenario.ScenarioStepR\x04body\x12\x19\n" +
	"\bdata_set\x18\x04 \x03(\tR\adataSet\"\xd2\x01\n" +
	"\n" +
	"PluginStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12Y\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v29.owaspattacksimulator.scenario.PluginStep.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\rScenarioEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vscenario_id\x18\x03 \x01(\tR\n" +
	"scenarioId\x12\x17\n" +
	"\astep_id\x18\x04 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xfa\x02\n" +
	"\x12StepExecutionEvent\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12X\n" +
	"\aresults\x18\x04 \x03(\v2>.owaspattacksimulator.scenario.StepExecutionEvent.ResultsEntryR\aresults\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8d\x03\n" +
	"\x0fScenarioService\x12\x83\x01\n" +
	"\x10ValidateScenario\x126.owaspattacksimulator.scenario.ValidateScenarioRequest\x1a7.owaspattacksimulator.scenario.ValidateScenarioResponse\x12z\n" +
	"\rParseScenario\x123.owaspattacksimulator.scenario.ParseScenarioRequest\x1a4.owaspattacksimulator.scenario.ParseScenarioResponse\x12x\n" +
	"\x0fExecuteScenario\x125.owaspattacksimulator.scenario.ExecuteScenarioRequest\x1a,.owaspattacksimulator.scenario.ScenarioEvent0\x01B1Z/github.com/owaspattacksimulator/api/proto;protob\x06proto3"

var (
	file_scenario_proto_rawDescOnce sync.Once
	file_scenario_proto_rawDescData []byte
)

func file_scenario_proto_rawDescGZIP() []byte {
	file_scenario_proto_rawDescOnce.Do(func() {
		file_scenario_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scenario_proto_rawDesc), len(file_scenario_proto_rawDesc)))
	})
	return file_scenario_proto_rawDescData
}

var file_scenario_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_scenario_proto_goTypes = []any{
	(*ValidateScenarioRequest)(nil),  // 0: owaspattacksimulator.scenario.ValidateScenarioRequest
	(*ValidateScenarioResponse)(nil), // 1: owaspattacksimulator.scenario.ValidateScenarioResponse
	(*ValidationError)(nil),          // 2: owaspattacksimulator.scenario.ValidationError
	(*ValidationWarning)(nil),        // 3: owaspattacksimulator.scenario.ValidationWarning
	(*ParseScenarioRequest)(nil),     // 4: owaspattacksimulator.scenario.ParseScenarioRequest
	(*ParseScenarioResponse)(nil),    // 5: owaspattacksimulator.scenario.ParseScenarioResponse
	(*ParseError)(nil),               // 6: owaspattacksimulator.scenario.ParseError
	(*ExecuteScenarioRequest)(nil),   // 7: owaspattacksimulator.scenario.ExecuteScenarioRequest
	(*ExecutionConfig)(nil),          // 8: owaspattacksimulator.scenario.ExecutionConfig
	(*Scenario)(nil),                 // 9: owaspattacksimulator.scenario.Scenario
	(*ScenarioStep)(nil),             // 10: owaspattacksimulator.scenario.ScenarioStep
	(*BrowserStep)(nil),              // 11: owaspattacksimulator.scenario.BrowserStep
	(*SessionStep)(nil),              // 12: owaspattacksimulator.scenario.SessionStep
	(*NetworkStep)(nil),              // 13: owaspattacksimulator.scenario.NetworkStep
	(*MutationConfig)(nil),           // 14: owaspattacksimulator.scenario.MutationConfig
	(*CheckConfig)(nil),              // 15: owaspattacksimulator.scenario.CheckConfig
	(*CrawlStep)(nil),                // 16: owaspattacksimulator.scenario.CrawlStep
	(*ControlStep)(nil),              // 17: owaspattacksimulator.scenario.ControlStep
	(*PluginStep)(nil),               // 18: owaspattacksimulator.scenario.PluginStep
	(*ScenarioEvent)(nil),            // 19: owaspattacksimulator.scenario.ScenarioEvent
	(*StepExecutionEvent)(nil),       // 20: owaspattacksimulator.scenario.StepExecutionEvent
	nil,                              // 21: owaspattacksimulator.scenario.ExecuteScenarioRequest.VariablesEntry
	nil,                              // 22: owaspattacksimulator.scenario.Scenario.VariablesEntry
	nil,                              // 23: owaspattacksimulator.scenario.Scenario.MetadataEntry
	nil,                              // 24: owaspattacksimulator.scenario.ScenarioStep.InputsEntry
	nil,                              // 25: owaspattacksimulator.scenario.ScenarioStep.GuardsEntry
	nil,                              // 26: owaspattacksimulator.scenario.ScenarioStep.EffectsEntry
	nil,                              // 27: owaspattacksimulator.scenario.ScenarioStep.MetadataEntry
	nil,                              // 28: owaspattacksimulator.scenario.BrowserStep.OptionsEntry
	nil,                              // 29: owaspattacksimulator.scenario.SessionStep.DataEntry
	nil,                              // 30: owaspattacksimulator.scenario.NetworkStep.HeadersEntry
	nil,                              // 31: owaspattacksimulator.scenario.MutationConfig.OptionsEntry
	nil,                              // 32: owaspattacksimulator.scenario.CheckConfig.ThresholdsEntry
	nil,                              // 33: owaspattacksimulator.scenario.CheckConfig.OptionsEntry
	nil,                              // 34: owaspattacksimulator.scenario.CrawlStep.OptionsEntry
	nil,                              // 35: owaspattacksimulator.scenario.PluginStep.ParametersEntry
	nil,                              // 36: owaspattacksimulator.scenario.StepExecutionEvent.ResultsEntry
	(*timestamppb.Timestamp)(nil),    // 37: google.protobuf.Timestamp
}
var file_scenario_proto_depIdxs = []int32{
	2,  // 0: owaspattacksimulator.scenario.ValidateScenarioResponse.errors:type_name -> owaspattacksimulator.scenario.ValidationError
	3,  // 1: owaspattacksimulator.scenario.ValidateScenarioResponse.warnings:type_name -> owaspattacksimulator.scenario.ValidationWarning
	9,  // 2: owaspattacksimulator.scenario.ParseScenarioResponse.scenario:type_name -> owaspattacksimulator.scenario.Scenario
	6,  // 3: owaspattacksimulator.scenario.ParseScenarioResponse.errors:type_name -> owaspattacksimulator.scenario.ParseError
	9,  // 4: owaspattacksimulator.scenario.ExecuteScenarioRequest.scenario:type_name -> owaspattacksimulator.scenario.Scenario
	21, // 5: owaspattacksimulator.scenario.ExecuteScenarioRequest.variables:type_name -> owaspattacksimulator.scenario.ExecuteScenarioRequest.VariablesEntry
	8,  // 6: owaspattacksimulator.scenario.ExecuteScenarioRequest.config:type_name -> owaspattacksimulator.scenario.ExecutionConfig
	22, // 7: owaspattacksimulator.scenario.Scenario.variables:type_name -> owaspattacksimulator.scenario.Scenario.VariablesEntry
	10, // 8: owaspattacksimulator.scenario.Scenario.steps:type_name -> owaspattacksimulator.scenario.ScenarioStep
	23, // 9: owaspattacksimulator.scenario.Scenario.metadata:type_name -> owaspattacksimulator.scenario.Scenario.MetadataEntry
	24, // 10: owaspattacksimulator.scenario.ScenarioStep.inputs:type_name -> owaspattacksimulator.scenario.ScenarioStep.InputsEntry
	25, // 11: owaspattacksimulator.scenario.ScenarioStep.guards:type_name -> owaspattacksimulator.scenario.ScenarioStep.GuardsEntry
	26, // 12: owaspattacksimulator.scenario.ScenarioStep.effects:type_name -> owaspattacksimulator.scenario.ScenarioStep.EffectsEntry
	10, // 13: owaspattacksimulator.scenario.ScenarioStep.children:type_name -> owaspattacksimulator.scenario.ScenarioStep
	27, // 14: owaspattacksimulator.scenario.ScenarioStep.metadata:type_name -> owaspattacksimulator.scenario.ScenarioStep.MetadataEntry
	28, // 15: owaspattacksimulator.scenario.BrowserStep.options:type_name -> owaspattacksimulator.scenario.BrowserStep.OptionsEntry
	29, // 16: owaspattacksimulator.scenario.SessionStep.data:type_name -> owaspattacksimulator.scenario.SessionStep.DataEntry
	30, // 17: owaspattacksimulator.scenario.NetworkStep.headers:type_name -> owaspattacksimulator.scenario.NetworkStep.HeadersEntry
	14, // 18: owaspattacksimulator.scenario.NetworkStep.mutation:type_name -> owaspattacksimulator.scenario.MutationConfig
	15, // 19: owaspattacksimulator.scenario.NetworkStep.checks:type_name -> owaspattacksimulator.scenario.CheckConfig
	31, // 20: owaspattacksimulator.scenario.MutationConfig.options:type_name -> owaspattacksimulator.scenario.MutationConfig.OptionsEntry
	32, // 21: owaspattacksimulator.scenario.CheckConfig.thresholds:type_name -> owaspattacksimulator.scenario.CheckConfig.ThresholdsEntry
	33, // 22: owaspattacksimulator.scenario.CheckConfig.options:type_name -> owaspattacksimulator.scenario.CheckConfig.OptionsEntry
	34, // 23: owaspattacksimulator.scenario.CrawlStep.options:type_name -> owaspattacksimulator.scenario.CrawlStep.OptionsEntry
	10, // 24: owaspattacksimulator.scenario.ControlStep.body:type_name -> owaspattacksimulator.scenario.ScenarioStep
	35, // 25: owaspattacksimulator.scenario.PluginStep.parameters:type_name -> owaspattacksimulator.scenario.PluginStep.ParametersEntry
	37, // 26: owaspattacksimulator.scenario.ScenarioEvent.timestamp:type_name -> google.protobuf.Timestamp
	36, // 27: owaspattacksimulator.scenario.StepExecutionEvent.results:type_name -> owaspattacksimulator.scenario.StepExecutionEvent.ResultsEntry
	37, // 28: owaspattacksimulator.scenario.StepExecutionEvent.started_at:type_name -> google.protobuf.Timestamp
	37, // 29: owaspattacksimulator.scenario.StepExecutionEvent.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 30: owaspattacksimulator.scenario.ScenarioService.ValidateScenario:input_type -> owaspattacksimulator.scenario.ValidateScenarioRequest
	4,  // 31: owaspattacksimulator.scenario.ScenarioService.ParseScenario:input_type -> owaspattacksimulator.scenario.ParseScenarioRequest
	7,  // 32: owaspattacksimulator.scenario.ScenarioService.ExecuteScenario:input_type -> owaspattacksimulator.scenario.ExecuteScenarioRequest
	1,  // 33: owaspattacksimulator.scenario.ScenarioService.ValidateScenario:output_type -> owaspattacksimulator.scenario.ValidateScenarioResponse
	5,  // 34: owaspattacksimulator.scenario.ScenarioService.ParseScenario:output_type -> owaspattacksimulator.scenario.ParseScenarioResponse
	19, // 35: owaspattacksimulator.scenario.ScenarioService.ExecuteScenario:output_type -> owaspattacksimulator.scenario.ScenarioEvent
	33, // [33:36] is the sub-list for method output_type
	30, // [30:33] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_scenario_proto_init() }
func file_scenario_proto_init() {
	if File_scenario_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scenario_proto_rawDesc), len(file_scenario_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scenario_proto_goTypes,
		DependencyIndexes: file_scenario_proto_depIdxs,
		MessageInfos:      file_scenario_proto_msgTypes,
	}.Build()
	File_scenario_proto = out.File
	file_scenario_proto_goTypes = nil
	file_scenario_proto_depIdxs = nil
}
