// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: scenario.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScenarioService_ValidateScenario_FullMethodName = "/owaspchecker.scenario.ScenarioService/ValidateScenario"
	ScenarioService_ParseScenario_FullMethodName    = "/owaspchecker.scenario.ScenarioService/ParseScenario"
	ScenarioService_ExecuteScenario_FullMethodName  = "/owaspchecker.scenario.ScenarioService/ExecuteScenario"
)

// ScenarioServiceClient is the client API for ScenarioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Scenario definition service
type ScenarioServiceClient interface {
	ValidateScenario(ctx context.Context, in *ValidateScenarioRequest, opts ...grpc.CallOption) (*ValidateScenarioResponse, error)
	ParseScenario(ctx context.Context, in *ParseScenarioRequest, opts ...grpc.CallOption) (*ParseScenarioResponse, error)
	ExecuteScenario(ctx context.Context, in *ExecuteScenarioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScenarioEvent], error)
}

type scenarioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScenarioServiceClient(cc grpc.ClientConnInterface) ScenarioServiceClient {
	return &scenarioServiceClient{cc}
}

func (c *scenarioServiceClient) ValidateScenario(ctx context.Context, in *ValidateScenarioRequest, opts ...grpc.CallOption) (*ValidateScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateScenarioResponse)
	err := c.cc.Invoke(ctx, ScenarioService_ValidateScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioServiceClient) ParseScenario(ctx context.Context, in *ParseScenarioRequest, opts ...grpc.CallOption) (*ParseScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseScenarioResponse)
	err := c.cc.Invoke(ctx, ScenarioService_ParseScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioServiceClient) ExecuteScenario(ctx context.Context, in *ExecuteScenarioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScenarioEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScenarioService_ServiceDesc.Streams[0], ScenarioService_ExecuteScenario_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteScenarioRequest, ScenarioEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScenarioService_ExecuteScenarioClient = grpc.ServerStreamingClient[ScenarioEvent]

// ScenarioServiceServer is the server API for ScenarioService service.
// All implementations must embed UnimplementedScenarioServiceServer
// for forward compatibility.
//
// Scenario definition service
type ScenarioServiceServer interface {
	ValidateScenario(context.Context, *ValidateScenarioRequest) (*ValidateScenarioResponse, error)
	ParseScenario(context.Context, *ParseScenarioRequest) (*ParseScenarioResponse, error)
	ExecuteScenario(*ExecuteScenarioRequest, grpc.ServerStreamingServer[ScenarioEvent]) error
	mustEmbedUnimplementedScenarioServiceServer()
}

// UnimplementedScenarioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScenarioServiceServer struct{}

func (UnimplementedScenarioServiceServer) ValidateScenario(context.Context, *ValidateScenarioRequest) (*ValidateScenarioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateScenario not implemented")
}
func (UnimplementedScenarioServiceServer) ParseScenario(context.Context, *ParseScenarioRequest) (*ParseScenarioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseScenario not implemented")
}
func (UnimplementedScenarioServiceServer) ExecuteScenario(*ExecuteScenarioRequest, grpc.ServerStreamingServer[ScenarioEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteScenario not implemented")
}
func (UnimplementedScenarioServiceServer) mustEmbedUnimplementedScenarioServiceServer() {}
func (UnimplementedScenarioServiceServer) testEmbeddedByValue()                         {}

// UnsafeScenarioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScenarioServiceServer will
// result in compilation errors.
type UnsafeScenarioServiceServer interface {
	mustEmbedUnimplementedScenarioServiceServer()
}

func RegisterScenarioServiceServer(s grpc.ServiceRegistrar, srv ScenarioServiceServer) {
	// If the following call pancis, it indicates UnimplementedScenarioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScenarioService_ServiceDesc, srv)
}

func _ScenarioService_ValidateScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).ValidateScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_ValidateScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).ValidateScenario(ctx, req.(*ValidateScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioService_ParseScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServiceServer).ParseScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioService_ParseScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServiceServer).ParseScenario(ctx, req.(*ParseScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioService_ExecuteScenario_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteScenarioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScenarioServiceServer).ExecuteScenario(m, &grpc.GenericServerStream[ExecuteScenarioRequest, ScenarioEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScenarioService_ExecuteScenarioServer = grpc.ServerStreamingServer[ScenarioEvent]

// ScenarioService_ServiceDesc is the grpc.ServiceDesc for ScenarioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScenarioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "owaspchecker.scenario.ScenarioService",
	HandlerType: (*ScenarioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateScenario",
			Handler:    _ScenarioService_ValidateScenario_Handler,
		},
		{
			MethodName: "ParseScenario",
			Handler:    _ScenarioService_ParseScenario_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteScenario",
			Handler:       _ScenarioService_ExecuteScenario_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scenario.proto",
}
