version: 1
name: "Browser Automation Test"
description: "Test browser automation with form filling and clicking"

# Global variables
vars:
  base_url: "https://platform.orbisguard.com"
  test_username: "blue_man92@windowslive.com"
  test_password: "Asd123!!!!"

# Session configuration
session:
  enabled: true

# Attack configuration
attack:
  enabled: true
  concurrency: 3
  payload_sets: ["xss.reflected"]

# Scenario steps
steps:

  # Step 1: Navigate to home page
  - id: navigate_home
    type: browser:navigate
    url: "{{ vars.base_url }}"
    wait: "domcontentloaded"
    description: "Navigate to home page"

  # Step 2: Handle Cloudflare challenge (if present)
  - id: handle_cloudflare
    type: browser:click
    description: "Handle Cloudflare challenge"
    selectors:
      - sel: "input[type='checkbox']"
      - sel: ".cb-lb input[type='checkbox']"
      - sel: "label.cb-lb input[type='checkbox']"
      - sel: "#LsMgo8 input[type='checkbox']"
      - sel: ".cb-c input[type='checkbox']"
      - sel: "[role='alert'] input[type='checkbox']"

  # Step 3: Click login button
  - id: login_page
    type: browser:click
    description: "Click login button"
    selectors:
      - sel: "ul.account-top > li.account-title > a"
      - sel: "a[href*='login']"
      - sel: "a:contains('Login')"
      - sel: "a:contains('Giriş')"
      - sel: "button:contains('Login')"
      - sel: "button:contains('Giriş')"

  # Step 2: Fill login form
  - id: login_form
    type: browser:fill
    description: "Fill username and password"
    selectors:
      - sel: "input[name='username']"
        value: "{{ vars.test_username }}"
      - sel: "input[name='password']"
        value: "{{ vars.test_password }}"
      - sel: "input[type='email']"
        value: "{{ vars.test_username }}"
      - sel: "input[type='password']"
        value: "{{ vars.test_password }}"
      - sel: "input[placeholder*='email']"
        value: "{{ vars.test_username }}"
      - sel: "input[placeholder*='password']"
        value: "{{ vars.test_password }}"

  # Step 3: Click login button
  - id: submit_login
    type: browser:click
    description: "Click login button"
    selectors:
      - sel: "button[type='submit']"
      - sel: "input[type='submit']"
      - sel: "button:contains('Login')"
      - sel: "button:contains('Sign in')"
      - sel: "button:contains('Giriş')"

# Success handling
on_success:
  - type: report:generate
    format: "json"
    output: "reports/browser_automation_results.json"
    description: "Generate automation test results"
