version: 1
name: "Simple API Attack Scenario"
description: "Simple attack against public API endpoints"

# Global variables
vars:
  base_url: "https://httpbin.org"

# Session configuration (disabled for simple attack)
session:
  enabled: false

# Attack configuration
attack:
  enabled: true
  concurrency: 3
  payload_sets: ["xss.reflected", "sqli.error"]

# Scenario steps
steps:
  # Step 1: Attack GET endpoint
  - id: attack_get_endpoint
    type: net:attack
    target: "{{ vars.base_url }}/get"
    method: "GET"
    parameters:
      - id
      - q
      - search
      - query
    payload_sets: ["xss.reflected"]
    description: "Attack GET endpoint with XSS payloads"

  # Step 2: Attack POST endpoint
  - id: attack_post_endpoint
    type: net:attack
    target: "{{ vars.base_url }}/post"
    method: "POST"
    parameters:
      - name
      - email
      - message
    payload_sets: ["xss.reflected", "sqli.error"]
    description: "Attack POST endpoint with XSS and SQLi payloads"

  # Step 3: Generate report
  - id: generate_report
    type: report:generate
    format: "html"
    output: "reports/simple_attack_report.html"
    description: "Generate attack report"

# Success handling
on_success:
  - type: report:generate
    format: "json"
    output: "reports/simple_attack_results.json"
    description: "Generate JSON results"
