version: 1
name: "Simple Test Scenario"
description: "Simple test scenario with working URLs"

# Global variables
vars:
  base_url: "https://httpbin.org"

# Session configuration
session:
  enabled: false

# Attack configuration
attack:
  enabled: true
  concurrency: 3
  payload_sets: ["xss.reflected"]

# Scenario steps
steps:
  # Step 1: Simple attack
  - id: test_attack
    type: net:attack
    target: "{{ vars.base_url }}/get"
    method: "GET"
    parameters:
      - id
      - q
    payload_sets: ["xss.reflected"]
    description: "Test attack against httpbin.org"

# Success handling
on_success:
  - type: report:generate
    format: "json"
    output: "reports/simple_test_results.json"
    description: "Generate test results"
